name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxext-dev

    - name: Build
      run: make
